version: "3.8"

services:
  postgres:
    env_file:
      - .env
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-ssv-rewards}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  sync:
    env_file:
      - .env
    build: .
    command: sync
    environment:
      NETWORK: ${NETWORK:-mainnet}
      POSTGRES: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-1234}@postgres/${POSTGRES_DB:-ssv-rewards}?sslmode=disable
      CONSENSUS_ENDPOINT: ${CONSENSUS_ENDPOINT}
      EXECUTION_ENDPOINT: ${EXECUTION_ENDPOINT}
      E2M_ENDPOINT: ${E2M_ENDPOINT}
      BEACONCHA_ENDPOINT: ${BEACONCHA_ENDPOINT}
      BEACONCHA_API_KEY: ${BEACONCHA_API_KEY}
      BEACONCHA_REQUESTS_PER_MINUTE: ${BEACONCHA_REQUESTS_PER_MINUTE}
    volumes:
      - ./:/app
      - ./data:/app/data

  calc:
    env_file:
      - .env
    build: .
    command: calc
    environment:
      POSTGRES: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-1234}@postgres/${POSTGRES_DB:-ssv-rewards}?sslmode=disable
    volumes:
      - ./:/app
