// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ContractEvents        string
	State                 string
	ValidatorEvents       string
	ValidatorPerformances string
	Validators            string
}{
	ContractEvents:        "contract_events",
	State:                 "state",
	ValidatorEvents:       "validator_events",
	ValidatorPerformances: "validator_performances",
	Validators:            "validators",
}
