// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ContractEvents        string
	Deployers             string
	OwnerRedirects        string
	State                 string
	ValidatorEvents       string
	ValidatorPerformances string
	ValidatorRedirects    string
	Validators            string
}{
	ContractEvents:        "contract_events",
	Deployers:             "deployers",
	OwnerRedirects:        "owner_redirects",
	State:                 "state",
	ValidatorEvents:       "validator_events",
	ValidatorPerformances: "validator_performances",
	ValidatorRedirects:    "validator_redirects",
	Validators:            "validators",
}
